#!/usr/bin/env php
<?php

require_once __DIR__ . '/load.php';

set_time_limit(0);

use App\Lib\Google\Drive\DefaultClient;
use RedisQueue\Client as RedisQueueClient;
use RedisQueue\Message;
use RedisQueue\Worker;

class WorkerBackup extends Worker
{
    public function do(Message $message)
    {
        $cmd = $message->cmd;
        print("--------\n");
        print("CMD: $cmd\n");
        if ($cmd === 'upload') {
            $this->upload($message);
        } elseif ($cmd === 'upload_video') {
            $this->upload_video($message);
        }
        print("--------\n");
    }

    protected function upload($message)
    {
        $lock_file = ROOT_PATH . '/upload.lock';
        touch($lock_file);
        $data = get_data();
        $item = null;
        foreach ($data as $path => $status) {
            if (!$status) {
                $item = $path;
                break;
            }
        }
        if (!$item) {
            @unlink($lock_file);
            return;
        }
        console_log("Zip...");
        $root_path = realpath($item);
        $files = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($root_path),
            RecursiveIteratorIterator::LEAVES_ONLY
        );
        $name = basename($item);
        $zip_path = ROOT_PATH . "/$name.zip";
        try {
            $zip = new ZipArchive();
            $zip->open($zip_path, ZipArchive::CREATE | ZipArchive::OVERWRITE);
            foreach ($files as $file) {
                // Skip directories (they would be added automatically)
                if (!$file->isDir()) {
                    // Get real and relative path for current file
                    $filePath = $file->getRealPath();
                    $relativePath = substr($filePath, strlen($root_path) + 1);

                    // Add current file to archive
                    $zip->addFile($filePath, $relativePath);
                }
            }
            $zip->close();
            console_log("Zip completed.");
            $defaultClient = new DefaultClient(ROOT_PATH . '/google_credentials.json', ROOT_PATH . '/token.json');
            console_log("Upload file...");
            $defaultClient->uploadFile($zip_path, "$name.zip", 'application/zip');
            console_log("Upload completed.");
            $data = get_data();
            $data[$item] = true;
            file_put_contents(ROOT_PATH . '/data.json', json_encode($data));
        } catch (Exception $e) {
            console_log("ERROR: " . $e->getMessage());
        }
        @unlink($lock_file);
        @unlink($zip_path);
    }

    protected function upload_video($message)
    {
        $lock_file = ROOT_PATH . '/upload.lock';
        touch($lock_file);
        $data = get_video();
        $item = null;
        foreach ($data as $path => $status) {
            if (!$status) {
                $item = $path;
                break;
            }
        }
        if (!$item) {
            @unlink($lock_file);
            return;
        }
        console_log("Create MP4...");
        $root_path = realpath($item);
        $video = basename($root_path);
        try {
            $size = '1080';
            $path = "$root_path/$size/.m3u8";
            $content = file_get_contents($path);
            $content = preg_replace("/(\d+.ts)/", "$root_path/$size/$1", $content);
            $content = str_replace('URI="key_url"', 'URI="' . $root_path . '/key"', $content);
            file_put_contents("$root_path/$size.m3u8", $content);
            @unlink("$root_path/$video.mp4");
            exec("ffmpeg -allowed_extensions ALL -i \"$root_path/$size.m3u8\" -codec copy $root_path/$video.mp4");
            @unlink("$root_path/$size.m3u8");
            console_log("MP4 completed.");
            $defaultClient = new DefaultClient(ROOT_PATH . '/google_credentials.json', ROOT_PATH . '/token.json');
            console_log("Upload file...");
            $defaultClient->uploadFile("$root_path/$video.mp4", "$video.mp4", 'video/mp4');
            console_log("Upload completed.");
            $data = get_video();
            $data[$item] = true;
            file_put_contents(ROOT_PATH . '/video.json', json_encode($data));
        } catch (Exception $e) {
            console_log("ERROR: " . $e->getMessage());
        }
        @unlink($lock_file);
        @unlink("$root_path/$video.mp4");
    }
}

try {
    $lock_file = ROOT_PATH . '/upload.lock';
    @unlink($lock_file);
    $client = new RedisQueueClient();
    $client->loop('backup_video_queue', new WorkerBackup());
} catch (Exception $e) {
    print($e->getMessage() . "\n");
}
